### ISSUE TITLE
[Feature Request]: Plugin Support

### ISSUE THREAD

**Issue by Mqxx** [LukenSkyne/Minecraft-Ping-Wheel#21]
Hey, I love this mod. Would it be possible that besides the mod you would also release a plugin for PaperMC? Similar to [this one](https://github.com/SandResidence/PingWheelBukkit 'PingWheelBukkit').

I would appreciate native support from this repository, not only for modded servers like Fabric, but also for plugin servers like PurpurMC, because I think many people like to use this mod on servers that are not modded servers.

I also think that you don't need a huge config for the plugin. Maybe just that you could restrict certain channels or something like that.

Thanks for consideration. 👍🏻

**Comment by RXJpaw** [comment]
Providing native support for Bukkit servers was mentioned during development but was discarded due to the lack of demand.
Reading your feature request provides us with more motivation to push such a plugin to production. 

This plugin wouldn't be programmed for Paper or any other Spigot work specificly but in the Bukkit (Spigot) environmentto provide support for every Bukkit fork.

We don't plan on restricting users by server-side configs in any way. If such a plugin would be created natively there wouldn't be any user-restricting configurations for admins to set.

Please don't expect us to provide Ping Wheel users with a plugin in the near future. We made the mod for fabric specifically and providing partial support for Bukkit would create extra stress on maintaining the mod.

**Comment by RXJpaw** [comment]
Providing native support for Bukkit servers was mentioned during development but was discarded due to the lack of demand.
Reading your feature request provides us with more motivation to push such a plugin to production. 

This plugin wouldn't be programmed for Paper or any other Spigot work specificly but in the Bukkit (Spigot) environment to provide support for every Bukkit fork.

We don't plan on restricting users by server-side configs in any way. If such a plugin would be created natively there wouldn't be any user-restricting configurations for admins to set.

Please don't expect us to provide Ping Wheel users with a plugin in the near future. We made the mod for fabric specifically and providing partial support for Bukkit would create extra stress on maintaining the mod.

**Comment by RXJpaw** [comment]
Providing native support for Bukkit servers was mentioned during development but was discarded due to the lack of demand.
Reading your feature request provides us with more motivation to push such a plugin to production. 

This plugin wouldn't be programmed for Paper or any other Spigot work specifically but in the Bukkit (Spigot) environment to provide support for every Bukkit fork.

We don't plan on restricting users by server-side configs in any way. If such a plugin would be created natively there wouldn't be any user-restricting configurations for admins to set.

Please don't expect us to provide Ping Wheel users with a plugin in the near future. We made the mod for fabric specifically and providing partial support for Bukkit would create extra stress on maintaining Ping Wheel.

**Comment by RXJpaw** [comment]
Hello again..

My keyboard stumbled over my cat and somehow [this repo](https://github.com/RXJpaw/Minecraft-Ping-Wheel-Plugin) got released?

You can download the plugin on the mentioned repo or [CurseForge](https://legacy.curseforge.com/minecraft/bukkit-plugins/ping-wheel-plugin)/[Bukkit](https://dev.bukkit.org/projects/ping-wheel-plugin)/[Modrinth](https://modrinth.com/plugin/ping-wheel-plugin/) when it gets approved by the moderators.

**Comment by Mqxx** [comment]
Thats so cool! Thanks a lot!

**Comment by RXJpaw** [comment]
Hope you tested it already and it works as intended on the mentioned bukkit forks.

**Comment by RXJpaw** [comment]
Just to avoid confusion. This plugin didn't work until 4 days ago.
