### ISSUE TITLE
[Feature Request]: Server-to-Client Waypoint Marking with Custom Text Descriptions

### ISSUE THREAD

**Issue by andreasdc** [LukenSkyne/Minecraft-Ping-Wheel#24]
Hey, can you add a feature that will bring sending pings with custom texts? To mark server side locations like spawn, npc, etc.

**Comment by LukenSkyne** [comment]
Hey, I understand your request as some sort of waypoint system, which I was not planning to implement since there are mods that do a really good job on that. Please elaborate on the functionality you are thinking of in terms of "custom text pings".

**Comment by andreasdc** [comment]
What mods are you thinking about? I meant for example marking a boss for all players.

**Comment by LukenSkyne** [comment]
For waypoints I'm thinking of minimap mods such as Xaero's. Can you explain how you expect to ping a boss differently from the current ping system? I don't understand the idea with custom text.

**Comment by andreasdc** [comment]
Server -> client waypoints? Marking server side location with a text, then sending them to client, after joining a world, dynamically etc.

**Comment by LukenSkyne** [comment]
I totally get where you're coming from!
This feature seems very fitting for client-side waypoint mods. They could integrate server-side waypoints like the Points of Interest from [Bluemap](https://bluecolored.de/bluemap/) for example.
However, this concept doesn't seem to fit with the purpose of Ping Wheel, which is aimed towards temporary, on-the-fly communication rather than persistent map features.

**Comment by andreasdc** [comment]
So there's no mod for that and you don't want to add that? :/

**Comment by LukenSkyne** [comment]
Really sorry, but I just feel like this belongs more into other mods. I am not sure if the functionality exists in another mod... I just know of the afforementioned server/client map mods

**Comment by andreasdc** [comment]
Would be nice, but if you say so
