### ISSUE TITLE
[Feature Request]: Increase Correction Period Option

### ISSUE THREAD

**Issue by nco2k** [LukenSkyne/Minecraft-Ping-Wheel#33]
it would be cool if you could change the correction period time limit option from 5s to 60s. this would allow us to use the same value as the ping duration, which would effectively make every player only have one active marker at a time.

edit: speaking of values, why is ping duration an integer and correction period a float? for consistency reasons, can you make both variables use the same type?

**Comment by LukenSkyne** [comment]
Thanks for bringing this to my attention!

For now, you could increase the correction period in the config file, but keep in mind that it is a client-side setting, so it only affects your pings.

The user interface limits the correction period to between 0.1 and 5 seconds, since most players will use a value around 1 seconds (the default), so the slider should have an appropriate range for that.
I will probably address this similar to the maximum range slider, to have some sort of "always replace" value.

The type difference is simply explained by the scales, the correction period could be seen as a "millisecond" value, while a ping duration below one second doesn't make sense.

**Comment by LukenSkyne** [comment]
This is now introduced in v1.9.0 🎉
