### ISSUE TITLE
Suggestions & Quality of Life

### ISSUE THREAD

**Issue by ConqAra** [LukenSkyne/Minecraft-Ping-Wheel#8]
- Ability to mute / not see pings option

- Maybe a feature that implements a team system so pings can only be shown for those in a party? This would probably lead to a config:
"Use team feature so pings are only shown from team members" if there's quite a bit of people,
OR automatically disable pings from non-team members and have a config: "Allow pings from non-team members" if you don't need the team feature!
I feel like this could be super beneficial in smps so only team members can see each other's pings!

**Comment by LukenSkyne** [comment]
I made a simple settings screen in version 1.2.0
The following is now configurable:
* the volume of pings
* the distance at which pings are drawn
* the "channel" on which you communicate your pings
  * this means only players on the same channel receive them
  * I thought this would be a straight-forward approach to the "team" idea, since it doesn't require any complex handshakes or chat commands
* item icons, which show the item texture (or model) instead of the ping icon

I hope this covers your ideas!
